# Generated by Django 2.0.2 on 2018-04-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20180320_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
