# Generated by Django 2.0.2 on 2018-04-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20180403_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_details',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
