# Generated by Django 2.0.2 on 2018-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_movie_movie_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_name',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
