# Generated by Django 2.0.2 on 2018-04-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_offers_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price_cl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='price_ex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='price_pr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
