# Generated by Django 2.0.2 on 2018-04-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(default='Nadiad', max_length=100),
            preserve_default=False,
        ),
    ]
