# Generated by Django 2.0.2 on 2018-04-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='price_cl',
        ),
    ]
