# Generated by Django 2.0.2 on 2018-04-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_remove_show_price_cl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
