# Generated by Django 2.0.2 on 2018-04-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_auto_20180405_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='seat',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100),
            preserve_default=False,
        ),
    ]
