# Generated by Django 2.0.2 on 2018-04-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_show_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
