# Generated by Django 2.0.2 on 2018-04-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_auto_20180405_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='offer_id',
            field=models.ForeignKey(default=6, on_delete='true', to='login.Offers'),
            preserve_default=False,
        ),
    ]
