# Generated by Django 2.0.2 on 2018-04-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_ticket_offer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puser',
            name='phoneno',
            field=models.CharField(max_length=30),
        ),
    ]
