# Generated by Django 2.0.2 on 2018-04-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_auto_20180405_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketoffer',
            name='offer_id',
        ),
        migrations.RemoveField(
            model_name='ticketoffer',
            name='ticket_id',
        ),
        migrations.DeleteModel(
            name='TicketOffer',
        ),
    ]
